# Generated by Django 4.0 on 2022-12-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='stud_id',
            field=models.CharField(max_length=200),
        ),
    ]
