# Generated by Django 4.1.3 on 2022-12-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0002_alter_votes_vote_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='votetracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.IntegerField()),
                ('vote_count', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='votes',
            name='vote_count',
        ),
    ]
