# Generated by Django 4.1.3 on 2022-12-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0003_votetracker_remove_votes_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votetracker',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatevotetracker', to='evoting.candidateprofile'),
        ),
    ]
